services:
  s_web:
    build: .
    container_name: 'test-node-server'
    ports:
      - '9000:3000'
    depends_on:
      s_redis:
        condition: service_started
      s_db:
        condition: service_healthy
        restart: true
    environment:
      - DATABASE_URL=mysql://root:mypassword@s_db:3306/fake_db_name
      - REDIS_HOST=s_redis
  s_redis:
    image: redis
    container_name: 'test-redis'
    ports:
      - '6379:6379'
  s_db:
    image: mysql
    container_name: 'test-mysql-db'
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'fake_db_name'
      MYSQL_ROOT_PASSWORD: 'mypassword'
    healthcheck:
      # test: ["CMD", "mysqladmin", "ping"]
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      # test: ["CMD", "mysql", "-e", "SELECT 1"]
      # test: ["CMD", "mysql", "-e", "SHOW DATABASES"]
      interval: 5s
      timeout: 3s
      retries: 5