version: '3'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    # environment:
    #   DATABASE_URL: 'mysql://root:rootroot@db:3306/xxx'
    depends_on:
      - db
  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'xxx'
      MYSQL_ROOT_PASSWORD: 'mypassword'