nginxconf: |
    server {
      listen 80;
      server_name _;
      location / {
        proxy_pass http://nodejs-service.default.svc.cluster.local:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

indexjs: |
    const http = require('http');

    const server = http.createServer((req, res) => {
      res.statusCode = 200;
      res.setHeader('Content-Type', 'text/plain');
      res.end('Hello, World!\n');
    });

    server.listen(3000, () => {
      console.log('Server running at http://127.0.0.1:3000/');
    });